### PR TITLE
Add --wait, -w flag to run-task

### PR DESCRIPTION
**Pull request by stephanme**
When the wait flag is supplied to run-task, the cli will not exit until the task enters a terminal state; SUCCEEDED or FAILED.

The cli exits 0 when the task succeeds and exits 1 when the task fails.

This improves the scriptability of tasks. They can be run serially in a script.

Cherry-pick of 8671a5b (#1861) to v8
Addresses Issue #1104, #2238

Authored-by: Zach Robinson <zrobinson@pivotal.io>
Co-authored-by: Stephan Merker <stephan.merker@sap.com>

## Does this PR modify CLI v6, CLI v7, or CLI v8?

CLI v8

## Description of the Change

Adds --wait flag to run-task command as available in CLI v7.

## Why Is This PR Valuable?

This improves the scriptability of tasks. They can be run serially in a script.
The --wait flag is supported for the run-task command in v7.

## Why Should This Be In Core?

New cmd line flag for existing core command.

## Applicable Issues

#2238

Original issue for v7 was #1104

## How Urgent Is The Change?

not urgent

## Other Relevant Parties

n/a

### CODE REVIEW

**Review by a-b — APPROVED** [review]
LGTM

**Comment by a-b** [comment]
Hi @stephanme, can you please fix EasyCLA? So we can proceed with merging this PR.

**Comment by stephanme** [comment]
I fixed the CLA check by taking over authorship of the cherry-picked commit.

**Comment by jdgonzaleza** [comment]
LGTM

**Review by jdgonzaleza — APPROVED** [review]

**Comment by remsikr** [comment]
Hello,
when `--wait, -w flag to run-task` will be available in `v8`?

**Pull request merged**
