### PR TITLE
Add state to buildpacks output

### LINKED ISSUE #2344: Re-open #1952
It was our assumption that `cf buildpacks` should now list a `state` column, but it's not. Tested with `cf version 8.5.0+73aa161.2022-09-12`.

I guess [this is the line](https://github.com/cloudfoundry/cli/blob/2201c608a95c65da071fc264cb3f4477d58cb6b6/command/v7/buildpacks_command.go#L51) where the table columns are defined and `state` is missing although CAPI returns that information.

### PR DESCRIPTION
**Pull request by philippthun**
Fixes #2344. See #1952 (original issue) for more details.

## Where this PR should be backported?

- [x] [main](https://github.com/cloudfoundry/cli/tree/main) - all changes should by default start here
- [x] [v8](https://github.com/cloudfoundry/cli/tree/v8)
- [ ] [v7](https://github.com/cloudfoundry/cli/tree/v7)

### CODE REVIEW

**Review by a-b — APPROVED** [review]

**Comment by moleske** [comment]
some integration tests are failing, posting an example failure so folks don't have to comb the integration tests in github themselves

```
 buildpacks command when the targeted API supports stack association [It] lists the buildpacks with the stack column 
/home/runner/work/cli/cli/integration/v7/isolated/buildpacks_command_test.go:51

  No future change is possible.  Bailing out early after 0.084s.
  Got stuck at:
      
      
      position   name                                                         stack        enabled   locked   state   filename
      1          staticfile_buildpack                                         cflinuxfs3   true      false    READY   staticfile_buildpack-cflinuxfs3-v1.6.2.zip
      2          staticfile_buildpack                                         cflinuxfs4   true      false    READY   staticfile_buildpack-cflinuxfs4-v1.6.2.zip
      3          java_buildpack                                               cflinuxfs3   true      false    READY   java-buildpack-cflinuxfs3-v4.58.zip
      4          java_buildpack                                               cflinuxfs4   true      false    READY   java-buildpack-cflinuxfs4-v4.58.zip
      5          ruby_buildpack                                               cflinuxfs3   true      false    READY   ruby_buildpack-cflinuxfs3-v1.10.1.zip
      6          ruby_buildpack                                               cflinuxfs4   true      false    READY   ruby_buildpack-cflinuxfs4-v1.10.1.zip
      7          dotnet_core_buildpack                                        cflinuxfs3   true      false    READY   dotnet-core_buildpack-cflinuxfs3-v2.4.10.zip
      8          dotnet_core_buildpack                                        cflinuxfs4   true      false    READY   dotnet-core_buildpack-cflinuxfs4-v2.4.10.zip
      9          nodejs_buildpack                                             cflinuxfs3   true      false    READY   nodejs_buildpack-cflinuxfs3-v1.8.9.zip
      10         nodejs_buildpack                                             cflinuxfs4   true      false    READY   nodejs_buildpack-cflinuxfs4-v1.8.9.zip
      11         go_buildpack                                                 cflinuxfs3   true      false    READY   go_buildpack-cflinuxfs3-v1.10.8.zip
      12         go_buildpack                                                 cflinuxfs4   true      false    READY   go_buildpack-cflinuxfs4-v1.10.8.zip
      13         python_buildpack                                             cflinuxfs3   true      false    READY   python_buildpack-cflinuxfs3-v1.8.9.zip
      14         python_buildpack                                             cflinuxfs4   true      false    READY   python_buildpack-cflinuxfs4-v1.8.9.zip
      15         php_buildpack                                                cflinuxfs3   true      false    READY   php_buildpack-cflinuxfs3-v4.6.4.zip
      16         php_buildpack                                                cflinuxfs4   true      false    READY   php_buildpack-cflinuxfs4-v4.6.4.zip
      17         nginx_buildpack                                              cflinuxfs3   true      false    READY   nginx_buildpack-cflinuxfs3-v1.2.2.zip
      18         nginx_buildpack                                              cflinuxfs4   true      false    READY   nginx_buildpack-cflinuxfs4-v1.2.2.zip
      19         r_buildpack                                                  cflinuxfs3   true      false    READY   r_buildpack-cflinuxfs3-v1.2.1.zip
      20         r_buildpack                                                  cflinuxfs4   true      false    READY   r_buildpack-cflinuxfs4-v1.2.1.zip
      21         binary_buildpack                                             cflinuxfs3   true      false    READY   binary_buildpack-cflinuxfs3-v1.1.4.zip
      22         binary_buildpack                                             cflinuxfs4   true      false    READY   binary_buildpack-cflinuxfs4-v1.1.4.zip
      23         INTEGRATION-BUILDPACK-19139db0-0d5f-4ca5-6f86-6e70a1e8fc02   cflinuxfs3   true      false    READY   buildpack-archive-file-705305173.zip
      24         INTEGRATION-BUILDPACK-5e25088b-2c8d-4c46-46c8-56e5259bfb19   cflinuxfs3   true      false    READY   buildpack-archive-file-1650460258.zip
      
  Waiting for:
      position\s+name\s+stack\s+enabled\s+locked\s+filename

  /home/runner/work/cli/cli/integration/v7/isolated/buildpacks_command_test.go:56
```

Basically in https://github.com/cloudfoundry/cli/blob/main/integration/v7/isolated/buildpacks_command_test.go#L56 (and maybe others?) the integration tests are looking for a specific list of column names and the new `state` column is not accounted for

**Comment by ccjaimes** [comment]
Hey @philippthun, we are looking to merge this PR. Could you kindly create an additional PR with these changes pointing to v8 branch please?

**Comment by philippthun** [comment]
> Hey @philippthun, we are looking to merge this PR. Could you kindly create an additional PR with these changes pointing to v8 branch please?

Here is the corresponding PR against the v8 branch: #2699

**Review by ccjaimes — APPROVED** [review]
LGTM! Thanks for this contribution

**Pull request merged**
