### PR TITLE
Submodule cfnetworking api code

### PR DESCRIPTION
**Pull request by joachimvaldez**
[#150351738]

@chinangela and I were unsure how to submodule this in. We basically copied the entire "api/cfnetworking" folder into a new [github repo](https://github.com/cloudfoundry-incubator/cfnetworking-cli-api), and submoduled that repo into the "api/cfnetworking" path.

If you have any suggestions on a better way to do this, please let us know and we'll update the PR!

### CODE REVIEW

**Comment by XenoPhex** [comment]
We don't submodule, we vendor code via GVT: https://github.com/FiloSottile/gvt

This means you'll have to add the code to our vendor and then update the actor imports to use the vendored version.

**Comment by joachimvaldez** [comment]
gotcha, makes sense

**Comment by dkoper** [comment]
Also, please ensure you have a LICENSE and CFF NOTICE file in your new repo, and both a vendored too into our repo. 
We have to follow this process https://github.com/cloudfoundry/cli/wiki/License-and-Notice-Files.

**Comment by joachimvaldez** [comment]
Closing this, opening this one: https://github.com/cloudfoundry/cli/pull/1224

**Pull request closed without merging**
