### PR TITLE
Add route_service_url support for cups

### PR DESCRIPTION
**Pull request by markstgodard**
Hi Simon et al

This PR is to add route_service_url support when creating user provided services  (i.e.  -r route_service_url)

Please see [#101430114] for more information
https://www.pivotaltracker.com/story/show/101430114

Cheers

### CODE REVIEW

**Comment by shalako** [comment]
At CLI team's request, we'll add a validation to return a meaningful error when API doesn't support the new option.

**Comment by markstgodard** [comment]
Will update to include the CC version validation and error message,  and will resubmit..
Cheers

**Comment by shalako** [comment]
Per @krishicks, the CLI team has decided to address a version checking strategy themselves later. So this PR is ready for evaluation.

**Comment by markstgodard** [comment]
Closing as per Shannon, we will resubmit after

**Pull request closed without merging**
