### PR TITLE
Attempt to translate UAA prompts to user local

### PR DESCRIPTION
**Pull request by drnic**
If UAA provides standard prompts (Email, Password) then the CLI can translate
them into the user's locale; else will display the prompt provided by UAA platform
operator.

This PR includes sample translation for Spanish by @frodenas.

```
$ cf config --locale es_ES
$ out/cf login -a https://api.dev.cfdev.sh --skip-ssl-validation
API endpoint: https://api.dev.cfdev.sh

Correo electrónico> user

Contraseña>
Authenticating...
OK
```

## Does this PR modify CLI v6 or v7?

It is for the login.go subsystem which I think is shared between v6 + v7.

## Description of the Change

Currently the `cf login` UX prints out whatever locale text that is provided by the UAA, irrespective of the end user's preference.

This PR attempts to help by attempting to translate default text into locale specific versions. 

This PR includes Spanish for Email + Password.

## Why Is This PR Valuable?

The users of Cloud Foundry should have very diverse native languages and we will helpful them by allowing them to fully experience CF in their native language.

## Why Should This Be In Core?

It is a fix for the `cf login` sequence.

## Applicable Issues

This was discussed in https://cloudfoundry.slack.com/archives/C03FXANBV/p1556578042010900

## How Urgent Is The Change?

Not urgent.

## Other Relevant Parties

* This change will help/override the default settings from their UAA configuration.

### CODE REVIEW

**Comment by abbyachau** [comment]
Thanks @drnic, as mentioned  [here](https://github.com/cloudfoundry/cli/issues/1617#issuecomment-486341531) we are currently rewriting `login`  - as a result you may need to rebase as we are making changes to this command, and we won't be able to review this in until the `cf login` rewriting effort is near completion. If there's any particular urgency with this pr, let us know, thanks.

**Comment by drnic** [comment]
Can this PR be merged now, so its included in the rewrite?

Or are you doing locale translation differently in the rewrite?

**Comment by abbyachau** [comment]
Hi @drnic really sorry for the delay. We had to postpone the rewrite due to a few client credentials related issues which we are just about to complete. We will be picking up the `cf login` refactor soon, and I'll review this pull request again with the engineering team once the refactor is actually underway again. It might take some time for us to get back to you on this but once we've ramped up on the `cf login` refactor, we'll revert. Thanks for you patience.

**Comment by heyjcollins** [comment]
Hello @drnic - I've recently rolled onto the CLI team as PM and I'm curious if this PR still stands given the current login implementation?

**Pull request merged**
