### PR TITLE
Arm64 release v7

### PR DESCRIPTION
**Pull request by gflex**
#2395 for v7
## Where this PR should be backported?

- [ ] [main](https://github.com/cloudfoundry/cli/tree/main)
- [ ] [v8](https://github.com/cloudfoundry/cli/tree/v8)
- [X] [v7](https://github.com/cloudfoundry/cli/tree/v7)

## Description of the Change
Edit pipelines to produce release for Linux arm64 arch.
included are linux binary, RPM and deb packages

## Why Is This PR Valuable?
We need to be able to run the CLI from linux/arm64 architectures.
Chances are we're not in deep need to run it from our RPI's but from linux containers on top of M1/2... Mac. 

## Applicable Issues
https://github.com/cloudfoundry/cli/pull/2395
https://github.com/cloudfoundry/cli/issues/2338
https://github.com/cloudfoundry/cli/issues/2293

### CODE REVIEW

**Review by a-b — APPROVED** [review]
LGTM @Benjamintf1

**Comment by gflex** [comment]
validations can be re-triggered now

**Comment by gflex** [comment]
uh, windows unit tests? Seems distant to our work here.

**Comment by gflex** [comment]
Validation issues do not relate to the content of PR. https://github.com/cloudfoundry/cli/pull/2518 should have fixed the problem

**Review by a-b — APPROVED** [review]

**Pull request merged**
