### PR TITLE
Added a new command create-ldap-user

### PR DESCRIPTION
**Pull request by mcintyred**
Hi,

### Motivation
This PR add a new command to allow operators to create a new user in environments which use LDAP for authentication. 

In these environments the process of onboarding a user is typically:

  - platform operator emails user inviting them to log in to the platform
  - user logs in for the first time and is informed that they need to contact the platform operator in order to be assigned org and space.
  - user emails operator
  - operator assign roles
  - user logs back in

With the ability to create a user in the UAA with origin="ldap", this process becomes:

  - platform operator runs cf create-ldap-user, cf set-org-role...
  - platform operator emails user
  - user logs in and starts working

This command is also helps operators to develop automated scripts to sync users' org/space roles across foundations e.g. in multi-data-center environments.

### Usage
cf create-ldap-user ldap-username ldap-path
e.g.
cf create-ldap-user new.user@myco.com cn=1234,ou=MYCORD,dc=Dev,dc=HQ,dc=MYCO

### CODE REVIEW

**Comment by fhanik** [comment]
Wouldn't it just be simpler to add `origin` and `external_id` as options to the `create-user` command?

ie, why would this be limited to ldap only? what if I have 5-6 SAML providers?

**Comment by mcintyred** [comment]
@fhanik : Good question. 

  - specifying origin!=uaa implies that password is not required. I wasn't sure how to manage that in terms of a command requirement
  - what happens if someone mistypes the origin? AFAIK the UAA doesn't actually check the origin for validity.

Maybe it would be better to rewrite this as

cf create-external-user username origin externalid

**Comment by fhanik** [comment]
@mcintyred 

`cf create-external-user username origin externalid` is probably better. Not sure convinced that it would require an external command.

If you mistype the origin you're probably out of luck, just like if you mistype an email address

**Comment by dkoper** [comment]
I think it's too confusing to have a separate command. It should be obvious to our users: You want to create a user, you type `cf create-user`.
If this command is doing something very specific, it could move to a CLI plugin. Otherwise, we should look into enhancing `create-user`, ideally in a way that any obvious future potential providers could be catered for without breaking UX. E.g.:
`cf create-user USERNAME [PASSWORD] [--origin ORIGIN] [--external-id EXTERNAL_ID]`, where ORIGIN defaults to `uaa`.
Maybe the back-end can be enhanced to validate the origin name and reject unknown providers?

**Comment by mcintyred** [comment]
I would like a consistent UX with `cf create-user`, but if all user creation is done with `cf create-user` then I think the UX will actually be more confusing:

`cf create-user USERNAME PASSWORD`  - OK
`cf create-user USERNAME PASSWORD --origin ldap` - ERROR: password is not required, externalid is required.
`cf create-user USERNAME --origin uaa` - ERROR: password is required when origin=uaa, externalid is not required.

Supplying a password could become optional, but then `cf passwd` would need to be enhanced to allow administrators to set another user's password (which I think it should be anyway).

With `cf create-external-user USERNAME ORIGIN EXTERNALID` the UX becomes:

`cf create-external-user USERNAME ldap EXTERNALID` - OK
`cf create-external-user USERNAME uaa EXTERNALID` - ERROR: uaa is not an external provider

Regards,

Duncan

**Comment by dkoper** [comment]
Take a look at [`cf create-route`](http://cli.cloudfoundry.org/en-US/cf/create-route.html) how a bit of usage text and examples can help users figure out what arguments and options to set.
If setting an `externalId` implies the password is managed (and initialized) elsewhere, `cf create-user USERNAME [PASSWORD | EXTERNAL_ID] --origin ldap` may make more sense. Command help can explain which is for which.

Regards,
Dies Koper
CF CLI PM

**Comment by mcintyred** [comment]
OK. I'll rework this as `cf create-user`

**Comment by mcintyred** [comment]
Latest commit now gives this UX:

```
dmcintyre-mac:cli mcintyred$ ./out/cf create-user
FAILED
Incorrect Usage. Requires arguments

NAME:
   create-user - Create a new user

USAGE:
   Create a UAA authenticated user:
      cf create-user USERNAME PASSWORD

  Create an externally authenticated user:
      cf create-user USERNAME EXTERNAL_ID --origin ORIGIN



EXAMPLES:
   cf create-user j.smith@mydomain.com S3cr3t                                                  # UAA-authenticated user
   cf create-user j.smith@mydomain.com 'cn=1234,ou=MYCORD,dc=Dev,dc=HQ,dc=MYCO' --origin ldap  # LDAP-authenticated user

OPTIONS:
   --origin      User origin for externally (non-UAA) authenticated users. EXTERNAL_ID must be supplied
```

**Comment by dkoper** [comment]
FYI, I've asked the UAA PM @sreetummidi to review as I want to make sure the new UX is future-proof, and get suggestions on wording (we currently don't expose the project name UAA in any other command help).
I'd like to pick this up again after hearing from her.

**Comment by sreetummidi** [comment]
All looks good. Can you please add one more line to the example section

cf create-user j.smith@mydomain.com 'jsmith' --origin provider-alias  # SAML or OpenID Connect federated user

**Comment by dkoper** [comment]
Hi @mcintyred,

Apologies for the delays.
I have reviewed the command with Sree, and we want to suggest the following changes:

```
NAME:
   create-user - Create a new user

USAGE:
   Create a user account:
      cf create-user USERNAME PASSWORD

  Create a user account to map to a user in an external identity provider:
      cf create-user USERNAME --origin ORIGIN

EXAMPLES:
   cf create-user j.smith@mydomain.com S3cr3t          # internal user
   cf create-user j.smith@mydomain.com --origin ldap  # LDAP user
   cf create-user j.smith@mydomain.com --origin provider-alias # SAML or OpenID Connect federated user

OPTIONS:
   --origin      Origin for external users
```

To summarize:
* Added the example Sree suggested
* Removed external_id: UAA team says it's not used anymore
* Changed the wording to avoid the CF project name "UAA"
* Simplified the wording for the most common case

If you'd like to rebase and update your PR, I'll pull it into the backlog for my team to code review?

**Comment by dkoper** [comment]
Closing. Feel free to reopen or submit a new PR with the updates I suggested.

**Comment by sreetummidi** [comment]
@dkoper Can we do this work. We have a lot of customers asking for this feature as create-user is not functional for LDAP and SAML and is causing a lot of confusion.

**Comment by dkoper** [comment]
Resurrected in https://www.pivotaltracker.com/story/show/129997693.

**Pull request closed without merging**
