### PR TITLE
Enable creating a shared domain with a router_group_guid

### PR DESCRIPTION
**Pull request by markstgodard**
This PR is to allow creating a shared domain with a router group. This is required for enabling tcp routing in CF.

Pivotal tracker link for the story https://www.pivotaltracker.com/story/show/100980222

Regards,
@atulkc 
@mdelillo
(CF Routing team)

Resubmitted PR https://github.com/cloudfoundry/cli/pull/625 by @markstgodard and @yuzhangcmu 

Please close PR 625

### CODE REVIEW

**Comment by shalako** [comment]
At CLI team's request, we'll add a validation to return a meaningful error when API doesn't support the new option.

**Comment by simonleung8** [comment]
Hi @markstgodard, can you rebase this PR, thanks.

**Comment by shalako** [comment]
Per @krishicks, the CLI team has decided to address a version checking strategy themselves later.

**Comment by fordaz** [comment]
Please close this branch and use PR (https://github.com/cloudfoundry/cli/pull/679) instead.
Thanks,
Fermin.

**Pull request closed without merging**
