### PR TITLE
Add replace redis file

### PR DESCRIPTION
**Pull request by moleske**
- taken from https://github.com/cloudfoundry/cli/pull/3042/commits/8620013d532ebc182d6059479e8e072c14cf1bdb which was done on main and v8 already to resolve issues

cc @gururajsh, @chinigo and @Samze since all you all were on the pr that I linked to above

Thank you for contributing to the CF CLI! Please read the following:

* Please make sure you have implemented changes in line with the [contributing guidelines](https://github.com/cloudfoundry/cli/blob/main/.github/CONTRIBUTING.md)
* We're not allowed to accept any PRs without a signed CLA, no matter how small.
If your contribution falls under a company CLA but your membership is not public, expect delays while we confirm.
* All new code requires tests to protect against regressions.
* Contributions must be made against the appropriate branch. See the [contributing guidelines](https://github.com/cloudfoundry/cli/blob/main/.github/CONTRIBUTING.md)
* Contributions must conform to our [style guide](https://github.com/cloudfoundry/cli/wiki/CLI-Product-Specific-Style-Guide). Please reach out to us if you have questions.

## Description of the Change
add replace redis ops file like the v8 and main branches

We must be able to understand the design of your change from this description.
Keep in mind that the maintainer reviewing this PR may not be familiar with or
have worked with the code here recently, so please walk us through the concepts.

## Why Is This PR Valuable?
 cause v7 pipeline doesn't work on prs and it makes me sad
What benefits will be realized by the code change? What users would want this change? What user need is this change addressing? 

## Applicable Issues

List any applicable GitHub Issues here

## How Urgent Is The Change?
very assuming we want to keep v7 alive and running and up to date on dependencies
Is the change urgent? If so, explain why it is time-sensitive.

## Other Relevant Parties

Who else is affected by the change?

### CODE REVIEW

**Comment by moleske** [comment]
note to self - recreate https://github.com/cloudfoundry/cli/pull/3044 and https://github.com/cloudfoundry/cli/pull/3043 after merge so dependabot will actually run the integration tests

**Comment by moleske** [comment]
Integration failing cause it uses what is committed to v7, not what is in the pr (or at least that's my understanding, correct me please if that is wrong)

**Review by gururajsh — APPROVED** [review]
Thank you for taking care of this. 

LGTM

**Review by a-b — COMMENTED** [review]
LGTM

**Pull request merged**
