### PR TITLE
Update language files

### PR DESCRIPTION
**Pull request by simonleung8**
Latest language translation contributed by IBM

### CODE REVIEW

**Comment by dkoper** [comment]
Thanks!

Your PR seems to revert the Portugese translation of the cf syntax?
http://docs-cf-cli-edge.cfapps.io/pt-BR/cf/

**Comment by dkoper** [comment]
Also, that particular line is translated in all other languages except for Chinese (not sure if that got reverted previously or was never there). Is it intentionally skipped?

**Comment by jeffpak** [comment]
Hey, we merged this commit manually because there were a bunch of merge conflicts. I went ahead and doctored up all the issues, so everything is up to date now. Thanks Simon, going to close this PR!

**Comment by simonleung8** [comment]
@jeffpak Thanks for the effort. I will bring these issues to the translators.

**Pull request closed without merging**
