### PR TITLE
Implement revisions command

### PR DESCRIPTION
**Pull request by simonjohansson**
## Does this PR modify CLI v6 or v7?

v7

## Description of the Change

Added a command `cf revisions appName` that calls out to `/v3/apps/appGUID/revisions` and displays the revisions.

```
$ cf7 revisions testing-rolling
Getting revisions for app testing-rolling in org meehp / space maahp as admin...
OK

version   guid                                   description                                                                            created at
1         5764513a-2593-44a3-8a8e-5e0d47b60ccc   Initial revision.                                                                      2020-03-04T13:12:21Z
2         7353351e-9de6-4463-95f4-9ec198bf80fc   New droplet deployed. New environment variables deployed.                              2020-03-04T13:16:46Z
3         493f20f3-74ef-4da7-bd3c-2c906db6f711   New droplet deployed.                                                                  2020-03-04T13:18:58Z
4         87bc52e2-360b-4944-ba08-5c604b089707   New droplet deployed. New environment variables deployed. Rolled back to revision 1.   2020-03-04T13:20:30Z
5         71efe101-8abc-4e6a-bba1-e1eef74ce535   New droplet deployed. New environment variables deployed. Rolled back to revision 3.   2020-03-04T13:23:32Z
6         51b94d9c-b845-4540-9899-f373cdf1cbaf   New droplet deployed.                                                                  2020-03-05T09:44:37Z
```
## Why Is This PR Valuable?

To make it easier to roll back an application that was deployed with the rolling strategy.

## Why Should This Be In Core?

Since this is a upcoming core feature for CF.

## Applicable Issues

https://github.com/cloudfoundry/cli/issues/1907

## How Urgent Is The Change?

Not urgent, V3/V7 is still in beta

### CODE REVIEW

**Comment by simonjohansson** [comment]
Looks like the tests timed out in travis, they work fine on my machine.

**Comment by simonjohansson** [comment]
Ping pong.

**Comment by simonjohansson** [comment]
Ping again.

**Comment by heyjcollins** [comment]
Ah @simonjohansson - you've provided a PR for this. Thank you!
I'd love to share it with my team for review but can't do so 'till it makes it passed Travis CI.
If, after having a look, your not sure how to resolve, feel free to reach out to us in the [#cli](https://cloudfoundry.slack.com/archives/C032824SM) channel on CloudFoundry Slack.

**Comment by simonjohansson** [comment]
@heyjcollins as I mentioned above it looks like a timeout in Travis, the tests all pass on my machine. Ive tried to retrigger it with a bogus commit, but Travis doesn't seem to pick it up. Maybe someone from your end can trigger it?

**Comment by heyjcollins** [comment]
@simonjohansson - I'll have someone on the team have a look.

Just a heads up that we intend to make a subsequent update to this command based on UX research our design team has conducted.

This iteration should be considered experimental and subject to change in the near future and I'll make sure to say so in release notes.

Thanks again for your contribution!

Josh

**Pull request merged**
