### PR TITLE
feat: add tip to restart app when enabling ssh

### PR DESCRIPTION
**Pull request by wanddynosios**
## Does this PR modify CLI v6, CLI v7, or CLI v8?

v8

## Description of the Change

This PR adds a 'TIP' to restart the app when enabling ssh:

````
➜  out git:(v8) ✗ ./cf-cli_macosarm disable-ssh my-app
Disabling ssh support for app my-app as my-user...
OK

➜  out git:(v8) ✗ ./cf-cli_macosarm enable-ssh my-app 
Enabling ssh support for app my-app as my-user...
OK

TIP: An app restart is required for the change to take effect.
➜  out git:(v8) ✗ ./cf-cli_macosarm enable-ssh my-app
Enabling ssh support for app my-app as my-user...
ssh support for app 'my-app' is already enabled.
OK

TIP: An app restart may be required for the change to take effect.

````

Complies with [style guide](https://github.com/cloudfoundry/cli/wiki/CLI-Product-Specific-Style-Guide#tips)

## Why Is This PR Valuable?

As a cloud foundry operator I often get questions from customers about cf ssh "not working", because it is not obvious that a restart is necessary.

## Why Should This Be In Core?
-

## Applicable Issues

https://github.com/cloudfoundry/cli/issues/2133#issuecomment-855917538

## How Urgent Is The Change?
-

## Other Relevant Parties

-

### CODE REVIEW

**Review by a-b — APPROVED** [review]
LGTM

@wanddynosios, can you please create and link PRs for the `main` branch and potentially for `v7`?

**Comment by wanddynosios** [comment]
@a-b I created https://github.com/cloudfoundry/cli/pull/2360 and https://github.com/cloudfoundry/cli/pull/2361.

Thanks!

**Comment by beyhan** [comment]
I'm wondering what is missing to get this in?

**Comment by wanddynosios** [comment]
> I'm wondering what is missing to get this in? 

So am I. The PR has been reviewed a while ago already.

**Comment by beyhan** [comment]
I also asked in the CLI Slack channel https://cloudfoundry.slack.com/archives/C032824SM/p1686818021365519

**Pull request merged**
