### PR TITLE
Sorting the listing of applications by the application name when calling cf apps.

### PR DESCRIPTION
**Pull request by tricky42**
Sorting the output by the application name makes the output if the 
>cf apps 

call much easier to read and offers a stable order. 

Signed-off-by: Andreas Bucksteeg <andreas@bucksteeg.de>

### CODE REVIEW

**Comment by goehmen** [comment]
Hi @tanglisha Did you mean to link to a specific story rather than the Services API project?

**Comment by MalteJ** [comment]
+1 for this PR

**Comment by tricky42** [comment]
It looks like the Travis CI error is unrelated to my change in the pull request, or?

**Comment by simonleung8** [comment]
Hi @tricky42, thanks for the PR. Your PR did not cause the travis failure, it is a problem on our end.

However, the CLI codebase is test-driven, and your changes are not covered by tests. Could you backfill your changes with test cases?

**Comment by camelpunch** [comment]
Looks like apps_test is failing.

**Comment by camelpunch** [comment]
Closing due to failing tests. Feel free to rebase / reopen.

**Pull request closed without merging**
