### PR TITLE
`cf revisions` no longer reports EXPERIMENTAL notice [v8]

### PR DESCRIPTION
**Pull request by chinigo**
## Description of the Change

This commit changes the `cf revision` and `cf revisions` commands to no longer print a notice that the command is experimental.

## Why Is This PR Valuable?

The `cf revision` and `cf revisions` commands were introduced over 4 years ago and are no longer experimental.

## Applicable Issues

n/a

## How Urgent Is The Change?

Not urgent.

## Other Relevant Parties

None

## Related PRs

- #3060 - v7 
- #3061 - v8 (this PR)
- #3062 - main

### CODE REVIEW

**Review by a-b — APPROVED** [review]
LGTM

**Review by joaopapereira — CHANGES_REQUESTED** [review]
Given that the test was there to ensure that the message was present I do not think these tests make sense anymore.
If you come back to the code and see this test, it is strange 😄

**Comment by a-b** [comment]
While tests as they are right now could document the promotion of the command from experimental to the core. I +1 to @joaopapereira 's point - It's better to remove these tests at all.

**Comment by chinigo** [comment]
- Negative test assertions removed (including one whole file that contained nothing but).
- Moved the `revisions` and `revision` command into the `APPS` section of the `cf help` output.

**Comment by chinigo** [comment]
Updated PR to incorporate @Samze's [feedback on the `main` version of this PR](https://github.com/cloudfoundry/cli/pull/3062#discussion_r1708023172):

- `cf revision` remains in `EXPERIMENTAL` status.
- `cf revisions` is no longer in `EXPERIMENTAL` status.
- `cf rollback` is no longer in `EXPERIMENTAL` status.

**Review by Samze — APPROVED** [review]

**Review by joaopapereira — APPROVED** [review]
LGTM

**Pull request merged**
