### PR TITLE
implement the story of delete service instance that has keys

### PR DESCRIPTION
**Pull request by zhang-hua**
[#92185380]

Signed-off-by: zhang-hua <zhuadl@cn.ibm.com>

### CODE REVIEW

**Comment by zhang-hua** [comment]
@simonleung8 @jberkhahn please help us to review the PR for the story of deleting service instance that has keys. Thanks a lot!

@maximilien @xingzhou

**Comment by jberkhahn** [comment]
helllo @zhang-hua, a few issues with your PR: 
1. You're still not showing up in the CFIBMers github org, need to either join that or make your membership public before you can merge
2. We've changed the translation files a bit, could you rebase your PR on top of master?

Other than that this looks good.

**Comment by zhang-hua** [comment]
@simonleung8, @jberkhahn  please help us to merge this PR since this is the last one for service key on CLI side. @shalako is waiting for us to confirm this story. Thanks!

cc @maximilien

**Comment by jberkhahn** [comment]
Hey @zhang-hua 
We need you to rebase your PR on top of the current version of master. The translation files have changed so now there is a merge conflict. As soon as you take care of that we can merge this for you.

**Comment by jberkhahn** [comment]
Cool then, this looks good. merged.

**Pull request merged**
