### PR TITLE
bump grpc to v1.56.2 v8

### PR DESCRIPTION
**Pull request by jaristiz**
Thank you for contributing to the CF CLI! Please read the following:

* Please make sure you have implemented changes in line with the [contributing guidelines](https://github.com/cloudfoundry/cli/blob/main/.github/CONTRIBUTING.md)
* We're not allowed to accept any PRs without a signed CLA, no matter how small.
If your contribution falls under a company CLA but your membership is not public, expect delays while we confirm.
* All new code requires tests to protect against regressions.
* Contributions must be made against the appropriate branch. See the [contributing guidelines](https://github.com/cloudfoundry/cli/blob/main/.github/CONTRIBUTING.md)
* Contributions must conform to our [style guide](https://github.com/cloudfoundry/cli/wiki/CLI-Product-Specific-Style-Guide). Please reach out to us if you have questions.

## Where this PR should be backported?

- [ ] [main](https://github.com/cloudfoundry/cli/tree/main)
- [x] [v8](https://github.com/cloudfoundry/cli/tree/v8)
- [ ] [v7](https://github.com/cloudfoundry/cli/tree/v7)

## Description of the Change

Bumping google.golang.org/grpc to v1.56.2 

## Why Is This PR Valuable?

Up-to-date version

### CODE REVIEW

**Comment by a-b** [comment]
@jaristiz I can see that you closed v7 [backport PR](https://github.com/cloudfoundry/cli/pull/2487). Can you please reopen it?

**Comment by jaristiz** [comment]
> @jaristiz I can see that you closed v7 [backport PR](https://github.com/cloudfoundry/cli/pull/2487). Can you please reopen it?

That branch requires way more work as one of the `grpc` components changed its interface, that's the reason why I closed it, I could reopen it but manual work will need to be done in order to bump this dependency.

**Comment by jaristiz** [comment]
@a-b this pipeline has been shown inconsistent results on the reruns for the pipelines, which for me, from the outside look like fakes, is there something I can do from my side to get it green?

**Comment by pabloarodas** [comment]
@a-b is there something we can do to get this PR merged? We still need this bump to fix the CVEs in our smoke tests release.

**Pull request merged**
