### PR TITLE
Added command to get quota usage for org

### PR DESCRIPTION
**Pull request by SrinivasChilveri**
Provides routes, services and memory used by organization.

This is the PR for story #94171010

# cf org-quota-usage serviceQuotaOrg
Getting quota usage info for org serviceQuotaOrg as admin...

Routes     5/5
Services   7/7
Memory    512M/1G
OK

Any comments/suggestions are welcome to change the code/add test cases etc.

### CODE REVIEW

**Comment by jberkhahn** [comment]
Hey there,

We're currently in the process of ripping out codegangstaa, so cf/command_factory/factory.go is undergoing changes currently. Could you rebase on top of master so we can merge your pull request. 

Thanks!

**Comment by AmitRoushan** [comment]
Hi @jberkhahn ,

Apologies for the delay in responding. I was caught up with some version work.
Runtime team has suggested some improvement in implementations and endpoints for [org and space quota usage](https://github.com/cloudfoundry/cloud_controller_ng/pull/383). I am planning to add relevant changes after finishing up CC implementation .

Thanks 
@AmitRoushan

**Comment by goehmen** [comment]
hey @AmitRoushan Did you make the revisions for Org and for Space or just Org?  Were you going to add relevant changes here?  Also were you going to submit a PR for space quota?  If not, I have a story in my backlog for the CLI team to do the space quota work.  tjhx

**Comment by camelpunch** [comment]
It's been a couple of months. Please re-open if you'd like to do this work for the non-codegangsta architecture.

**Pull request closed without merging**
