### PR TITLE
Ensures that cf-deployment and bosh-deployment directories are proper…

### PR DESCRIPTION
**Pull request by willmadison**
…ly cloned to the correct location

### CODE REVIEW

**Comment by abbyachau** [comment]
Hi @willmadison thanks for this. If you could fill out some of the details next time you create a pull request, that would be helpful.

**Comment by willmadison** [comment]
Definitely! My apologies. I didn't realize there was a template as my muscle memory took over when I was creating it initially. I'll definitely take more care next time.

**Comment by abbyachau** [comment]
No problem @willmadison. Thanks for the pull request. :)

**Comment by Ema93sh** [comment]
Thank you

**Pull request merged**
