### PR TITLE
Add support for SHA256 SSH fingerprints

### PR DESCRIPTION
**Pull request by pivotal-danjahner**
This pull request adds support for verifying SHA256 hashes of the Diego SSH proxy public key. 

Existing functionality supports MD5 and SHA1 hashes, however, these hashes are widely deprecated for applications that require collision resistance. Further - [NIST Guidance][1], [General sentiment][2]

[1]:http://csrc.nist.gov/groups/ST/hash/policy.html
[2]:https://www.google.com/#q=sha1+support

### CODE REVIEW

**Comment by dkoper** [comment]
We had a discussion in #817 on this. Are you also working on updating the hash returned by CC /v2/info?

**Comment by pivotal-danjahner** [comment]
Hey Dies - 

The hash returned by /v2/info is purely pass-through from the configuration in the manifest. This pull request assumes the same format for SHA256 that is currently accepted for MD5 and SHA1, a hex string of the expected length. 

Referenced issue 87 includes a separate issue, which is that a base64 encoded SHA1 or SHA256 hash is not validated appropriately. I did not handle this in the PR, as that appears beyond the scope of generally accepting SHA256 hashes. 

If a user provides a hex-formatted hash or uses CredHub to automatically generate the SSH key, this will would work as expected. 

Here are some test examples that I used for this change - 

Positive case - 
```
jah:cli djahner$ out/cf curl /v2/info
{
   "name": "",
   "build": "",
   "support": "",
   "version": 0,
   "description": "",
   "authorization_endpoint": "https://login.cf.jahner.xyz",
   "token_endpoint": "https://uaa.cf.jahner.xyz",
   "min_cli_version": null,
   "min_recommended_cli_version": null,
   "api_version": "2.74.0",
   "app_ssh_endpoint": "ssh.cf.jahner.xyz:2222",
   "app_ssh_host_key_fingerprint": "36:07:ed:ed:8d:c0:6a:9d:11:a0:b4:d5:01:a3:b3:40:4d:4a:5f:3d:70:a3:76:e9:cf:3e:24:f4:a5:7b:4e:a0",
   "app_ssh_oauth_client": "ssh-proxy",
   "routing_endpoint": "https://api.cf.jahner.xyz/routing",
   "logging_endpoint": "wss://loggregator.cf.jahner.xyz:443",
   "doppler_logging_endpoint": "wss://doppler.cf.jahner.xyz:443",
   "user": "eea8afb8-5de5-4225-b86b-6f605dc50ef9"
}
jah:cli djahner$ out/cf ssh static
vcap@eb33769c-61a3-4659-4fe3-12c74f2311e5:~$ ...
```

Negative case (fingerprint specified does not match public key on machine)- 
```
jah:cli djahner$ out/cf curl /v2/info
{
   "name": "",
   "build": "",
   "support": "",
   "version": 0,
   "description": "",
   "authorization_endpoint": "https://login.cf.jahner.xyz",
   "token_endpoint": "https://uaa.cf.jahner.xyz",
   "min_cli_version": null,
   "min_recommended_cli_version": null,
   "api_version": "2.74.0",
   "app_ssh_endpoint": "ssh.cf.jahner.xyz:2222",
   "app_ssh_host_key_fingerprint": "46:07:ed:ed:8d:c0:6a:9d:11:a0:b4:d5:01:a3:b3:40:4d:4a:5f:3d:70:a3:76:e9:cf:3e:24:f4:a5:7b:4e:a0",
   "app_ssh_oauth_client": "ssh-proxy",
   "routing_endpoint": "https://api.cf.jahner.xyz/routing",
   "logging_endpoint": "wss://loggregator.cf.jahner.xyz:443",
   "doppler_logging_endpoint": "wss://doppler.cf.jahner.xyz:443",
   "user": "eea8afb8-5de5-4225-b86b-6f605dc50ef9"
}
jah:cli djahner$ out/cf ssh static
FAILED
Error opening SSH connection: ssh: handshake failed: Host key verification failed.

The fingerprint of the received key was "36:07:ed:ed:8d:c0:6a:9d:11:a0:b4:d5:01:a3:b3:40:4d:4a:5f:3d:70:a3:76:e9:cf:3e:24:f4:a5:7b:4e:a0".
```

**Comment by dkoper** [comment]
Hi Dan

Thanks for the quick reply.
Eric pointed out that `ssh-keygen -lf` on his ssh host public key returned a base-64 encoded string instead of hex-encoded with `:` separators on his Mac. Is there any particular reason for not aligning with that? (I noticed -E is not available on this command on my Ubuntu machine)
```
$ ssh-keygen -lf keypair/ssh-proxy-host-key.pem.pub -E md5
2048 MD5:e2:03:25:2f:88:2d:01:a5:fd:9d:9a:8e:3f:0e:4f:f7 pivotal@dickcissel (RSA)

$ ssh-keygen -lf keypair/ssh-proxy-host-key.pem.pub -E sha256
2048 SHA256:z45Qirucf6l+D6wMNSaoIA57HH4q0Sq+tgnxtGaliBs pivotal@dickcissel (RSA)
```

**Comment by pivotal-danjahner** [comment]
Base64 encoding is fine for me, I used hex to follow the convention of the existing SHA1 fingerprint.

**Comment by dkoper** [comment]
Looks like the convention changed between md5 and sha1 already and the CLI did not catch up. Let's not make that mistake again.

```
$ ssh-keygen -lf keypair/ssh-proxy-host-key.pem.pub -E sha1
2048 SHA1:XZxze8tPJpAMwuB2aGjx6Yt/yFE pivotal@dickcissel (RSA)
```

**Comment by pivotal-danjahner** [comment]
Hey Dies - 

This adds support for base64 encoded hashes (both SHA1 and SHA256).

**Comment by dkoper** [comment]
@pivotal-danjahner I'm getting push-back because the related CC property says "MD5". @zrob seems open to update that description if someone can confirm it works for other formats.
https://github.com/cloudfoundry/cloud_controller_ng/blob/master/bosh/jobs/cloud_controller_ng/spec#L81

Can you test it and submit a PR to update that property description?

**Comment by dkoper** [comment]
We're looking at merging the support for base64 sha256, which I believe satisfies the use case and was acceptable to you.

We will not add support at this time for all the variations. Note that whatever you add now we have to support for the rest of our lives. It doesn't make sense to add variations for MD5 and sha1 if we say they're widely deprecated.

Please consider updating the CC property description @zrob or @pivotal-danjahner 
https://github.com/cloudfoundry/cloud_controller_ng/blob/master/bosh/jobs/cloud_controller_ng/spec#L81

**Comment by pivotal-danjahner** [comment]
I think we always have the option to deprecate features during the life of a product, so I'm not sure I agree with the concept of 'supporting for the rest of our lives'. 

Regardless, the base64 SHA256 hash does fit the need that this was intended to solve. I'll reach out to CC about the job property description. Thanks!

**Pull request merged**
