### PR TITLE
Add --wait, -w flag to run-task

### PR DESCRIPTION
**Pull request by zrob**
When the wait flag is supplied to run-task, the cli will
not exit until the task enters a terminal state; SUCCEEDED or FAILED.

The cli exits 0 when the task succeeds and exits 1 when the task fails.

This improves the scriptability of tasks. They can be run
serially in a script.

Addresses Issue #1104

---

This affects v7 only.

Does not address the --log request in the associated issue.

### CODE REVIEW

**Comment by bwasmith** [comment]
Related stories in the backlog:
https://www.pivotaltracker.com/story/show/163546155
https://www.pivotaltracker.com/story/show/142560911
https://www.pivotaltracker.com/story/show/163546235

**Comment by JenGoldstrich** [comment]
Bumping this due to a user reaching out, we are planning on merging this PR for the first minor release post V7 GA :)!

**Comment by BitPatty** [comment]
What's the state on this PR, is it still being tracked?

**Comment by a-b** [comment]
I'd like to follow up to see if this PR is still relevant.

**Comment by Kiemes** [comment]
I would still like to get that feature. :)

**Comment by BitPatty** [comment]
> I would still like to get that feature. :)

Dito, would enormously improve the scriptability with the cf cli

**Comment by jkbschmid** [comment]
Any updates on this? I'd also like to use this in my scripts.

**Comment by a-b** [comment]
Our team is understaffed, and it could take a while to get to this via the backlog.
If someone wants to expedite this feature, please consider fixing conflicts, making tests green.
We will prioritize PR review without merge conflicts.

**Comment by zrob** [comment]
@a-b I've updated the PR to remove conflicts and to target v7 branch. hope that helps when you get a chance to review.

**Comment by a-b** [comment]
Thank you @zrob !
Can you please sign CLA by following EasyCLA directions so we can promptly merge your PR.

**Review by reedr3 — APPROVED** [review]
This looks good

**Comment by a-b** [comment]
@zrob is employed by VMware, so we are going to proceed with this merge.

**Pull request merged**
