### PR TITLE
`cf revisions` no longer reports EXPERIMENTAL notice [v7]

### PR DESCRIPTION
**Pull request by chinigo**
## Description of the Change

This commit changes the `cf revision` and `cf revisions` commands to no longer print a notice that the command is experimental.

## Why Is This PR Valuable?

The `cf revision` and `cf revisions` commands were introduced over 4 years ago and are no longer experimental.

## Applicable Issues

n/a

## How Urgent Is The Change?

Not urgent.

## Other Relevant Parties

None

## Related PRs

- #3060 - v7 (this PR) 
- #3061 - v8
- #3062 - main

### CODE REVIEW

**Review by a-b — COMMENTED** [review]
I'm questioning if these types of changes belong to V7, as V7 is at the end of its lifecycle. My understanding is that V7 receives security and bug fixes, while behavior changes belong to V8 and main (future V9).

**Comment by joaopapereira** [comment]
Since it is removing the Experimental warning, I am not sure we can consider this a new feature, it is more housekeeping now.

**Review by joaopapereira — CHANGES_REQUESTED** [review]
Given that the test was there to ensure that the message was present I do not think these tests make sense anymore.
If you come back to the code and see this test, it is strange 😄

**Comment by a-b** [comment]
@joaopapereira I did not say anything about a new feature. Removing `EXPERIMENTAL` from the cli output is a change to the output.

**Comment by chinigo** [comment]
- Negative test assertions removed (including one whole file that contained nothing but).
- Moved the `revisions` and `revision` command into the `APPS` section of the `cf help` output.

**Comment by chinigo** [comment]
Updated PR to incorporate @Samze's [feedback on the `main` version of this PR](https://github.com/cloudfoundry/cli/pull/3062#discussion_r1708023172):

- `cf revision` remains in `EXPERIMENTAL` status.
- `cf revisions` is no longer in `EXPERIMENTAL` status.
- `cf rollback` is no longer in `EXPERIMENTAL` status.

**Review by Samze — APPROVED** [review]

**Review by joaopapereira — APPROVED** [review]
LGTM

**Pull request merged**
