### PR TITLE
Refactor create-service-key command

### PR DESCRIPTION
**Pull request by ablease**
This PR adds a refactor for the `create-service-key` command.

https://www.pivotaltracker.com/story/show/160342879

This PR also includes adding an integration test when using the `create-service-key` command with an async service broker, and cleaning up the error message that occurs in this case. Please see [this comment](https://www.pivotaltracker.com/story/show/160231357) for more context.

Thanks,
Sapi Team,

Alex + @lurraca

### CODE REVIEW

**Comment by abbyachau** [comment]
Prioritised but blocked, see the tracker story for more details: we are currently updating our master branch and unfortunately @ablease this means we will need to either rebase once we nearly done or ask you folks to do so. The team will update you folks once we have the master branch work nearly completed but please do not hesitate to reach out in the meantime if you have any questions.

**Comment by XenoPhex** [comment]
Hey there SAPI Team!

The VAT team is taking a bit of a hammer to the `master` branch right now in order to support both V6 and V7 on master (crazy I know). We're hoping that this work will be complete over the next few days, but it might interfere with the work done by this pull request.

If you'd like, the VAT team can rebase this pull request after we've done all of our moving and shaking, or y'all can do it yourself at your leisure. Let us know what you decide!

If you're looking for a story to track the VAT team's work: https://www.pivotaltracker.com/story/show/160853831

Additionally, I'm documenting this work in the [Architecture-Guide](https://github.com/cloudfoundry/cli/wiki/Architecture-Guide) and the [New Contribution Guide](https://github.com/cloudfoundry/cli/blob/master/.github/CONTRIBUTING_NG.md) after the changes are made. (note: there might be some time lag on that documentation).

**Comment by Samze** [comment]
@XenoPhex Let's wait a few days until the refactoring dust settles and then we can see what is involved in doing the rebase. Could you let us know when it's largely done?

**Comment by XenoPhex** [comment]
@Samze Will do! We're hoping that everything should be done over the next few days.

**Pull request merged**
