### PR TITLE
better error reporting with feeded curl data is not enclosed.

### PR DESCRIPTION
**Pull request by Zouuup**
this will also help with this issue on PivotalTracker:
https://www.pivotaltracker.com/n/projects/892938/stories/95206110

### CODE REVIEW

**Comment by Zouuup** [comment]
emm, i think there was a problem with cfdreddbot, my newer PR #590 has CLA passed, do i need to resend PR?

**Comment by Zouuup** [comment]
there is a problem with corporate licence, i'll take care of that.

**Comment by camelpunch** [comment]
Your username is on the bot's whitelist, not sure why it didn't pick it up.

**Comment by camelpunch** [comment]
Minor: can we lower-case Argument in that error sentence please? Also, squashing the commits so we don't have undos in the history would be nice.

**Comment by Zouuup** [comment]
Done sir ;)

**Pull request merged**
