### PR TITLE
Updated cf push usage text to use CF_NAME

### PR DESCRIPTION
**Pull request by zhusulai**
Updated usage for cf push to usage CF_NAME, to be consistency with other commands.

### CODE REVIEW

**Comment by abbyachau** [comment]
Hey @zhusulai thanks for creating this pull request. Please could you sign the CLA and we can look into pulling this in. Thanks.

**Comment by zhusulai** [comment]
CLA has been signed and submitted.

**Comment by christopherclark** [comment]
@zhusulai I don't see a CLA on file for you.  Could you please sign and send one in to contributors@cloudfoundry.org?  If you've already signed and sent one, could you please forward that email to the above address?  Thank you.

**Comment by zhusulai** [comment]
@christopherclark I submitted the CLA again today. Hopefully it reaches you.

**Comment by christopherclark** [comment]
CLA A-OK

**Pull request merged**
