### PR TITLE
Service Instance Sharing is no longer Experimental

### PR DESCRIPTION
**Pull request by ablease**
This PR:
* Remove experimental warnings
* Move tests from experimental to global

[Story](https://www.pivotaltracker.com/story/show/152478613) on Service API tracker.

Thanks,
Luis & @Samze (Service API Team)

### CODE REVIEW

**Comment by Samze** [comment]
**Note**: Please hold off merging this PR until the CAPI changes have made it into a cf-deployment.

**Comment by Samze** [comment]
We do @XenoPhex https://www.pivotaltracker.com/story/show/159268096. I've blocked your tracker story on it. Thanks!

**Comment by mattmcneeney** [comment]
This feature is now in a cf-deployment so can be merged! Thanks!

**Comment by lurraca** [comment]
As soon as the PR is merged we would announce the feature to a broader audience, it would be good if CLI didn't showed the experimental warning for it.

@cloudfoundry/services-api

**Comment by mattmcneeney** [comment]
Ping @abbyachau @tjvman :)

**Comment by abbyachau** [comment]
Hey @matthewmcnew thanks - this is at the top of our soloist backlog - hope to get to this soon. Will definitely keep an eye out for it before we release (which might be end of month) to make sure we get to it.

**Comment by lurraca** [comment]
@tjvman thanks for the suggestion. The most recent commit should have all the required changes.

1) We missed that spot. We were concerned about the `EXPERIMENTAL` flag on the actual service instance sharing command and didn't tackle the "help all" command.

2) I am not a 100% sure what was the criteria used for putting the integration tests on `global` (I feel @Samze might be able to help on this), but as you mention since they were already in experimental that runs in parallel therefore it makes sense they continue to run parallel(global).

**Comment by jenspinney** [comment]
@lurraca @tjvman I think these tests need to be in the `global` suite since they turn on and off the service-instance sharing feature flag. It seems risky to run tests that modify the cf env in the parallel suite.

**Comment by mattmcneeney** [comment]
Thanks!

**Pull request merged**
