### PR TITLE
add task result to task_command output

### PR DESCRIPTION
**Pull request by saescha**
Thank you for contributing to the CF CLI! Please read the following:

* Please make sure you have implemented changes in line with the [contributing guidelines](https://github.com/cloudfoundry/cli/blob/main/.github/CONTRIBUTING.md)
* We're not allowed to accept any PRs without a signed CLA, no matter how small.
If your contribution falls under a company CLA but your membership is not public, expect delays while we confirm.
* All new code requires tests to protect against regressions.
* Contributions must be made against the appropriate branch. See the [contributing guidelines](https://github.com/cloudfoundry/cli/blob/main/.github/CONTRIBUTING.md)
* Contributions must conform to our [style guide](https://github.com/cloudfoundry/cli/wiki/CLI-Product-Specific-Style-Guide). Please reach out to us if you have questions.

## Where this PR should be backported?

- [ ] [main](https://github.com/cloudfoundry/cli/tree/main) - all changes should by default start here
- [ ] [v8](https://github.com/cloudfoundry/cli/tree/v8)
- [ ] [v7](https://github.com/cloudfoundry/cli/tree/v7)

## Description of the Change

We must be able to understand the design of your change from this description.
Keep in mind that the maintainer reviewing this PR may not be familiar with or
have worked with the code here recently, so please walk us through the concepts.

## Why Is This PR Valuable?

What benefits will be realized by the code change? What users would want this change? What user need is this change addressing? 

## Applicable Issues

List any applicable GitHub Issues here

## How Urgent Is The Change?

Is the change urgent? If so, explain why it is time-sensitive.

## Other Relevant Parties

Who else is affected by the change?

### CODE REVIEW

**Comment by ccjaimes** [comment]
Hey @saescha, we are looking to merge this PR. Could you please sign the CLA for us to proceed? Also, could you kindly please create a PR with these changes pointing to the relevant primary main branches, v7 and/or v8.

**Comment by d047491** [comment]
Hi,
I signed the CLA with both my github users (saescha and d047491) there was some confusion because i used saescha for Github but i signed the commit as d047491. 

I cherry-picked the commit to v7 and v8 of my fork but for some reason i am not able to create a PR with the error message:
Pull request creation failed. Validation failed: must be a collaborator

Could you create the PRs:
https://github.com/cloudfoundry/cli/compare/cloudfoundry:v8...saescha:v8?expand=1
and 
https://github.com/cloudfoundry/cli/compare/cloudfoundry:v7...saescha:v7?expand=1

**Comment by saescha** [comment]
Never mind. The problem was again being signed in with the wrong account:
https://github.com/cloudfoundry/cli/pull/2691
https://github.com/cloudfoundry/cli/pull/2692

**Comment by ccjaimes** [comment]
@saescha There is an integration test failing. I added in a commit on each branch an unit test case for specific scenario, could you please take a look into it?

**Comment by gururajsh** [comment]
Hi @saescha,

Looks like some integration tests are failing, can you please have a look?

**Pull request closed without merging**
