### PR TITLE
Update i18n resources

### PR DESCRIPTION
**Pull request by simonleung8**
This is the latest i18n translations contributed by IBM. It contains translation for all 9 languages.

### CODE REVIEW

**Comment by dkoper** [comment]
@simonleung8 I sent you some comments on slack, mainly about the new translations for `SEE ALSO`.

**Comment by nickwei84** [comment]
@simonleung8 @dkoper 
Looks like the merge conflicts is across the entire translation file for every language. We're not sure how we should resolve this. Also the newlines seem to be encoded incorrectly.

**Comment by simonleung8** [comment]
Accidentally closed it. 
Fixed the conflicts and reopening the PR.
@nickwei84 ^^

**Comment by dkoper** [comment]
Thanks Simon!

**Pull request merged**
