### PR TITLE
Add purge-service-instance command

### PR DESCRIPTION
**Pull request by utako**
Adds a `cf purge-service-instance` that will recursively delete a service instance, its keys and its service bindings.   

Tracker story is [here](https://www.pivotaltracker.com/story/show/102318490).

Best wishes,
@utako, CF CAPI Team

### CODE REVIEW

**Comment by krishicks** [comment]
Hi @utako,

We're no longer using `github.com/cloudfoundry/cli/flags/flag`. You'll need to update your PR:

```diff
diff --git a/cf/commands/service/purge_service_instance.go b/cf/commands/service/purge_service_instance.go
index d3d94b8..d04a7ef 100644
--- a/cf/commands/service/purge_service_instance.go
+++ b/cf/commands/service/purge_service_instance.go
@@ -7,8 +7,8 @@ import (
 	. "github.com/cloudfoundry/cli/cf/i18n"
 	"github.com/cloudfoundry/cli/cf/requirements"
 	"github.com/cloudfoundry/cli/cf/terminal"
-	"github.com/cloudfoundry/cli/flags"
-	"github.com/cloudfoundry/cli/flags/flag"
+	"github.com/simonleung8/flags"
+	"github.com/simonleung8/flags/flag"
 )
 
 type PurgeServiceInstance struct {
```

(You can apply that diff directly by copying it (make sure to get the newline after the last line!), then using `pbpaste | git apply --ignore-whitespace`. )

See b6ca76f for when we made the switch.

It'd also be super if you would rebase your branch.

Let me know if you want any help with the above.

**Comment by utako** [comment]
Hey @krishicks,

I've made the changes you requested, and the branch `purge_service_instance_102318490` on my fork has been rebased. Let me know if you need anything else.

Thanks,
@utako

**Comment by krishicks** [comment]
@utako,

You'll need to update it again, but this time amending the previous commit as the previous commit isn't able to be built, and therefore isn't a green commit which passes tests.

You can do it easily with the following:

```bash
git co purge_service_instance_102318490
git reset HEAD~1
git ci -a --amend -CHEAD
git push -f git@github.com:utako/cli.git HEAD:purge_service_instance_102318490
```

**Comment by utako** [comment]
@krishicks,

it should already be done and it looks like it's green.

**Pull request merged**
