### PR TITLE
Change how space tip is presented to user - add quotes.  Fixes #580

### LINKED ISSUE #580: Tip printed for 'create-space' should contain quotes to handle orgs & spaces with literal spaces in the name
Example:

```
% cf create-space "Production Space" -o "Org Name"
...[snip]...
TIP: Use 'cf target -o Org Name -s Production Space' to target new space
```

Which won't work in most shells.  It should print instead:

```
TIP: Use 'cf target -o "Org Name" -s "Production Space"' to target new space
```

### PR DESCRIPTION
**Pull request by mcowger**
Changes how the space tip is presented, and Fixes issue #580

### CODE REVIEW

**Comment by camelpunch** [comment]
Hey @mcowger! Thanks for the PR. As the bot says, we need to ensure you've signed the CLA before merging even a trivial text change like this. Perhaps you could join a GitHub org that you know has already signed?

**Comment by mcowger** [comment]
I've sent over the CLA to the CF.org people already - I'm sure they can work it out.  I work for EMC, which has already signed, but EMC doesn't let most employees join their GitHub org (life at big companies!), including me :(.  I'm a member of the emccode org, but thats separate.

I totally understand the need to wait to merge until we have the stuff signed.  I just prefer to get stuff done and send over the PRs while we wait for the business to catch up :).

**Comment by camelpunch** [comment]
@mcowger these are all of the currently permitted orgs:

  - 18F
  - 84codes
  - ActiveState
  - att-cloudfoundry
  - blueboxgroup
  - altoros
  - anynines
  - appfog
  - cfibmers
  - cfcisco
  - clarkparsia
  - cloudcredo
  - cloudfoundry
  - codethinklabs
  - ECSTeam
  - emcpcf
  - fareoffice
  - Forio
  - fujitsu-cf
  - hpcloud
  - HuaweiTech
  - ibm
  - innovationfactory
  - intalio
  - iron-io
  - libertymutual
  - lds-cf
  - mendix
  - nirds
  - nttlabs
  - nurego
  - OGIS-RI-EOS
  - Orange-OpenSource-Cf
  - piston
  - pivotal
  - pivotal-cf
  - Pivotal-Field-Engineering
  - pivotal-golang
  - rakutentech
  - redislabs
  - sap-cloudfoundry
  - sassoftware
  - searchbox-io
  - sendgrid
  - swisscom
  - symcfmembers
  - Tier3
  - uhurusoftware
  - vchs
  - velankanisys
  - zephirworks
  - ZJU-SEL

**Comment by mcowger** [comment]
I'm now a member of the emcpcf group which is on the list - should be good from a CLA perspective now.

**Pull request merged**
