### PR TITLE
Start using cflinuxfs3

### PR DESCRIPTION
**Pull request by joaopapereira**
## Description of the Change

This change will add a new opsfile to enable integration tests in edge to use cflinuxfs3.

### CODE REVIEW

**Review by moleske — COMMENTED** [review]
Why are we adding cflinuxfs3?  It is no longer support in the open source community.  I am vaguely aware of some companies providing private cflinuxfs3 as extended support but not convinced that is something we should be testing on this open source repo.  Especially as the repo is now [archived](https://github.com/cloudfoundry/cflinuxfs3-release) and the last release was in June 2023

**Comment by joaopapereira** [comment]
We are in the process of changing pools we are using to run tests for cli and to do that, we need to ensure that linuxfs-3 is present in the deployment, or else a big group of tests would have to be changed. This change is also necessary to support the current min capi version tests we will re-add.

Another point here is that we are planning on stopping support v7 around Oct, so the amount of changes that we would need to do is too big compared with just adding support for Linux-3 is too big for something that we plan on stopping supporting in a few months' time.

**Comment by moleske** [comment]
Definitely curious which tests need to change.  Though I'm assuming these tests are only on the v7 branch.

As long as this is old contained to the v7 branch, seems reasonable.

**Review by a-b — APPROVED** [review]
LGTM

**Pull request merged**
