### PR TITLE
Add support for port in create_route command

### PR DESCRIPTION
**Pull request by yuzhangcmu**
Add port flag "-p" to the create route command to be able to create a route with a given external port mapping. 

The story about the PR: https://www.pivotaltracker.com/story/show/100992242
 
Thanks,
@yuzhangcmu @fordaz

### CODE REVIEW

**Comment by yuzhangcmu** [comment]
#674

**Comment by shalako** [comment]
At CLI team's request, we'll add a validation to return a meaningful error when API doesn't support the new option.

**Comment by shalako** [comment]
Per @krishicks, the CLI team has decided to address a version checking strategy themselves later. So this PR is ready for evaluation.

**Comment by shalako** [comment]
I'll accept on a branch before we submit a PR.

**Pull request closed without merging**
